### ISSUE TITLE
Is It possible de use debrid-file.com to URLresolver?

### ISSUE THREAD

**Issue by sebsty** [Kodi-vStream/venom-xbmc-addons#3116]
Hi,
Is It possible de use debrid-file.com to URLresolver?
Thanks

**Comment by andykimpe** [comment]
je pense pas y a un recaptcha sur la page de connexion

de plus il envoie force-download en header

ce qui fait que le streaming ne marche pas même vlc ne reconnait pas leur lien

I don't think there is a recaptcha on the login page

I don't think there is a recaptcha on the login page

moreover it sends force-download in header

so that the streaming does not work even vlc does not recognize their link

par contre md serait pas mal comme ajout pour ma part j'utilise les 2 ad et md

 y a une api json pour md

https://www.mega-debrid.eu/index.php?page=api

**Comment by Arias800** [comment]
We do not handle URL Resolver, ask them directly on their own Github.
