### ISSUE TITLE
Problème captcha sur Apple TV 4

### ISSUE THREAD

**Issue by FloRidaBzH** [Kodi-vStream/venom-xbmc-addons#632]
Bonjour à tous,

tout d'abord bravo pour votre addon. J'ai découvert via un article sur kodi il y a un mois et je dois dire que c'est vraiment intuitif (hormis l'installation au départ mais bon)

Alors j'expose mon problème brièvement : 

j'utilise Kodi v17 Krypton (la dernière build dispo) pour apple tv 4 (TV OS 10)
j'ai installé la dernière version de vstream 0.4.6

Lorsque je veux visionner un film sur une source qui renvoi vers un captcha, je ne peux tout simplement pas le saisir. En effet, au lieu de me lancer le clavier virtuel de Kodi avec le captcha a réécrire au dessus, il me lance le clavier virtuel de l' apple tv. Je ne comprends pas bien pourquoi car au départ cel fonctionnait parfaitement. 

J'ai une autre install sur ma tv sony (android os) et tout fonctionne sans problème.

J'ai vérifié dans des options (kodi, apple tv et vstream) mais je ne trouve rien à modifier... Si quelqu'un à une solution ?...
Merci d'avance

**Comment by johngf** [comment]
Tu as essayé avec kodi16? la 17 est beta est va surement causé des bugs

**Comment by FloRidaBzH** [comment]
Ben justement, j'étais déjà sous jarvis. Sinon malheureusement il n'y a pas de building dite stable pour TvOs...

**Comment by Kodigoal** [comment]
et si t'envoi le captcha par une appli 'telecommande' kodi via ton tel ? kore sous android , ios ya aussi je crois .

**Comment by TmpName** [comment]
Yep, pour le moment Vstream ne gere pas la V17, on attend quelle soit officielle.

**Comment by FloRidaBzH** [comment]
Merci pour vos infos je fais le test de l'appli télécommande et je repasse en jarvis. Je fais un feedback des que possible. Ça pourra aider. Ce qui est étrange, du jour au lendemain ça me mets le clavier Apple tv alors qu au départ j'avais comme sous Android tv avec le captcha en haut avec le clavier de kodi

**Comment by FloRidaBzH** [comment]
![dsc_0239](https://cloud.githubusercontent.com/assets/23217069/19947465/8d69989e-a148-11e6-89d7-a4d742a782c2.JPG)
Voilà ce que j'ai à la place du clavier kodi. Je vois pas bien d'où ça vient. Je teste demain avec une autre build. Au pire je réinitialise mon Apple tv.

**Comment by TmpName** [comment]
Normallement ca va bugguer sur kodi V17, donc cette partie va etre corrigée, mais je sais pas encore quoi ni si ca va changer quelque chose pour toi.

**Comment by FloRidaBzH** [comment]
Oui ... L'idéal serait d'avoir un autre testeur sous Apple TV. Perso, je n'y connais rien en prog. Soit c'est l'application Kodi qui faut revoir ou bien vstream et ainsi forcer le clavier de l appli et on celle de l'Apple tv

**Comment by Flavien** [comment]
Avez-vous vérifié qu'il s'agisse d'un bug dans Kodi 17, et si oui, l'avez vous rapporté aux développeurs ?

**Comment by TmpName** [comment]
Ca ne marche pas sous kodi V17.
On attend la version officielle pour s'adapter.

**Comment by yankeebasque** [comment]
bonjour à tous,
je possède plusieurs Apple TV 4 et Vstream marche très bien sur Kodi Krypton 17.1
aucuns problème à signaler.
sauf que des fois impossible à installer Vstream sur Kodi Krypton, je ne comprend pourquoi ça marche sur certaines KODI sous krypton ( Application 17 ou 17.1 ) et pourquoi des fois je n'arrive pas à installer Vstream ( vous pouvez installer un autre ardon en français qui s'appelle  Ultrastream
 sur addon http://fusion.tvaddons.ag  ( international, et ensuite  seko )
je viens de faire les mises à jours et j'ai bien installer VSTREAM sur kodi Krypton et cela marche très bien. si vous avez besoin d'aide laisser un message

**Comment by johngf** [comment]
tu install vstream comment via ce repo https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/Repository
ou un autre repo qui n'est pas conseillé ?

**Comment by yankeebasque** [comment]
j'installe Vstream avec l'ADDON Fusion dont voici url http://fusion.tvaddons.ag
ensuite internationale et le repository French Vstream

**Comment by yankeebasque** [comment]
tu peux aussi installer avec l'addon suivant
http://ftp.acc.umu.se/mirror/addons.superrepo.org

**Comment by johngf** [comment]
Bah justement c'est pas conseillé et c'est pour ça que certains n'y arrive pas

**Comment by yankeebasque** [comment]
https://www.tvaddons.ag/kodi-addons/show/plugin.video.vstream/

**Comment by yankeebasque** [comment]
3 âme façon d'installer Vstream utiliser indigo

Installing Kodi Addons

You can install any Kodi addon you’d like using our Indigo tool for easy Kodi addon configuration and maintenance. It will allow you to browse through our unofficial Kodi addon library directly from your device, and do a whole lot of other cool things. If you have any questions, feel free to visit our discussion forums for assistance.

Kodi addons work by scraping content from online sources, content is displayed based on what those sources provide. This means that Kodi addon developers cannot be held responsible for content displayed through these Kodi addons, since they have no control over what content is hosted on the web sites they are scraping. The responsibility ultimately lies on the web sites from which index or host the content.

Kodi addons have nothing to do with the distribution of content. All they do is give the user the ability to access content that is already posted online. The content scraped by these Kodi addons comes straight from whichever online streaming sources that the developer of the particular Kodi addon has selected. Kodi addons will break from time to time, usually because the source they are scraping have changed something on their web site.

**Comment by Kodigoal** [comment]
Tu fais comme ca car tu peux pas télécharger/mettre le .zip du repo officiel d'ici donné par @johngf directement sur l'appleTV ( comme  avec les iphone/ipad non jailbreaké)  ? 
Le truc c'est que  parfois ils ont encore l'ancienne version du repo vStream , donc faut faire gaffe.
Pour ca qu'il faudrait héberger le zip  officiel du repo quelque part car sous ios non jailbreaké , tu peux pas installer le zip d'ici comme ca.

**Comment by LordVenom** [comment]
Ce sujet et clos merci de faire une nouvelle conversation.
